package InheritanceTasks.studentsTask.enums;

public enum Department {
    ACCOUNTING_DEPARTMENT,
    DEPARTMENT_OF_ANALYSIS_AND_AUDIT,
    DEPARTMENT_OF_INTERNATIONAL_LAW,
    DEPARTMENT_OF_CRIMINALISTICS,
    DEPARTMENT_OF_RUSSIAN_HISTORY,
    DEPARTMENT_OF_ARCHEOLOGY,
    DEPARTMENT_OF_NUCLEAR_PHYSICS,
    DEPARTMENT_OF_RADIOPHYSICS,
    DEPARTMENT_OF_ORGANIC_CHEMISTRY,
    DEPARTMENT_OF_INORGANIC_CHEMISTRY,
    DEPARTMENT_OF_COMPUTATIONAL_MATH,
    DEPARTMENT_OF_MATH_ANALYSIS
}
